export const DELETE_DOCUMENT ='DELETE_DOCUMENT';
export const POST_DOCUMENT ='POST_DOCUMENT';
export const FETCH_DOCUMENT ='FETCH_DOCUMENT';
export const FETCH_DOCUMENTS ='FETCH_DOCUMENTS';
export const MODIFY_DOCUMENT ='MODIFY_DOCUMENT';
export const SAVE_DOCUMENT ='SAVE_DOCUMENT';
export const ADD_MASTERDOCS='ADD_MASTERDOCS';
export const ADD_STOCKS='ADD_STOCKS';
export const SET_CURRENTCOMPANY='SET_CURRENTCOMPANY';
export const MODIFY_SETTING='MODIFY_SETTING';


export const FETCH_USERS ='FETCH_USERS';
export const LOADING_USERS ='LOADING_USERS';
export const ADD_USERS ='ADD_USERS';
export const FAILED_USERS ='FAILED_USERS';



// export const FETCH_TAXES ='FETCH_TAXES';
// export const LOADING_TAXES ='LOADING_TAXES';
// export const ADD_TAXES ='ADD_TAXES';
// export const FAILED_TAXES ='FAILED_TAXES';

// export const FETCH_TAXRATES ='FETCH_TAXRATES';
// export const LOADING_TAXRATES ='LOADING_TAXRATES';
// export const ADD_TAXRATES ='ADD_TAXRATES';
// export const FAILED_TAXRATES ='FAILED_TAXRATES';

// export const FETCH_TAXGROUPS ='FETCH_TAXGROUPS';
// export const LOADING_TAXGROUPS ='LOADING_TAXGROUPS';
// export const ADD_TAXGROUPS ='ADD_TAXGROUPS';
// export const FAILED_TAXGROUPS ='FAILED_TAXGROUPS';


// export const FETCH_TAXTYPES ='FETCH_TAXTYPES';
// export const LOADING_TAXTYPES ='LOADING_TAXTYPES';
// export const ADD_TAXTYPES ='ADD_TAXTYPES';
// export const FAILED_TAXTYPES ='FAILED_TAXTYPES';



// export const FETCH_ITEMS ='FETCH_ITEMS';
// export const LOADING_ITEMS ='LOADING_ITEMS';
// export const ADD_ITEMS ='ADD_ITEMS';
// export const FAILED_ITEMS ='FAILED_ITEMS';


// export const FETCH_PARTIES ='FETCH_PARTIES';
// export const LOADING_PARTIES ='LOADING_PARTIES';
// export const ADD_PARTIES ='ADD_PARTIES';
// export const FAILED_PARTIES ='FAILED_PARTIES';


// export const FETCH_PAYMODES ='FETCH_PAYMODES';
// export const LOADING_PAYMODES ='LOADING_PAYMODES';
// export const ADD_PAYMODES ='ADD_PAYMODES';
// export const FAILED_PAYMODES ='FAILED_PAYMODES';



// export const FETCH_GLACCOUNTS ='FETCH_GLACCOUNTS';
// export const LOADING_GLACCOUNTS ='LOADING_GLACCOUNTS';
// export const ADD_GLACCOUNTS ='ADD_GLACCOUNTS';
// export const FAILED_GLACCOUNTS ='FAILED_GLACCOUNTS';



// export const FETCH_PAYTERMS ='FETCH_PAYTERMS';
// export const LOADING_PAYTERMS ='LOADING_PAYTERMS';
// export const ADD_PAYTERMS ='ADD_PAYTERMS';
// export const FAILED_PAYTERMS ='FAILED_PAYTERMS';



// export const FETCH_STATES ='FETCH_STATES';
// export const LOADING_STATES ='LOADING_STATES';
// export const ADD_STATES ='ADD_STATES';
// export const FAILED_STATES ='FAILED_STATES';



// export const FETCH_COMPANIES ='FETCH_COMPANIES';
// export const LOADING_COMPANIES ='LOADING_COMPANIES';
// export const ADD_COMPANIES ='ADD_COMPANIES';
// export const FAILED_COMPANIES ='FAILED_COMPANIES';