const arrNames= 
 [
  {  value: "20 Microns",  label: "20 Microns"},
  {  value: "21st Cent. Mgmt.",  label: "21st Cent. Mgmt."},
  {  value: "3i Infotech",  label: "3i Infotech"},
  {  value: "3M India",  label: "3M India"},
  {  value: "3P Land Hold.",  label: "3P Land Hold."},
  {  value: "52 Weeks Enter.",  label: "52 Weeks Enter."},
  {  value: "5Paisa Capital",  label: "5Paisa Capital"},
  {  value: "63 Moons Tech.",  label: "63 Moons Tech."},
  {  value: "7NR Retail Ltd",  label: "7NR Retail Ltd"},
  {  value: "7Seas Enter.",  label: "7Seas Enter."},
  {  value: "A & M Febcon",  label: "A & M Febcon"},
  {  value: "A and M Jumbo",  label: "A and M Jumbo"},
  {  value: "A B B",  label: "A B B"},
  {  value: "A B Infrabuild",  label: "A B Infrabuild"},
  {  value: "A B M Internatl.",  label: "A B M Internatl."},
  {  value: "A F Enterprises",  label: "A F Enterprises"},
  {  value: "A Infrastructure",  label: "A Infrastructure"},
  {  value: "A K Spintex",  label: "A K Spintex"},
  {  value: "A R C Finance",  label: "A R C Finance"},
  {  value: "A.K.Capital Serv",  label: "A.K.Capital Serv"},
  {  value: "A-1 Acid",  label: "A-1 Acid"},
  {  value: "A2Z Infra Engg.",  label: "A2Z Infra Engg."},
  {  value: "AA Plus Trade",  label: "AA Plus Trade"},
  {  value: "AAA Technologies",  label: "AAA Technologies"},
  {  value: "Aadi Industries",  label: "Aadi Industries"},
  {  value: "Aakash Explor.",  label: "Aakash Explor."},
  {  value: "Aananda Lakshmi",  label: "Aananda Lakshmi"},
  {  value: "Aanchal Ispat",  label: "Aanchal Ispat"},
  {  value: "Aarey Drugs",  label: "Aarey Drugs"},
  {  value: "Aarnav Fashions",  label: "Aarnav Fashions"},
  {  value: "Aaron Industries",  label: "Aaron Industries"},
  {  value: "Aartech Solonics",  label: "Aartech Solonics"},
  {  value: "Aarti Drugs",  label: "Aarti Drugs"},
  {  value: "Aarti Industries",  label: "Aarti Industries"},
  {  value: "Aarti Surfactant",  label: "Aarti Surfactant"},
  {  value: "Aarvee Denims",  label: "Aarvee Denims"},
  {  value: "Aarvi Encon",  label: "Aarvi Encon"},
  {  value: "Aashka Hospitals",  label: "Aashka Hospitals"},
  {  value: "AAVAS Financiers",  label: "AAVAS Financiers"},
  {  value: "Aayush Food&Herb",  label: "Aayush Food&Herb"},
  {  value: "Aban Offshore",  label: "Aban Offshore"},
  {  value: "ABans Enterprise",  label: "ABans Enterprise"},
  {  value: "Abbott India",  label: "Abbott India"},
  {  value: "ABC India",  label: "ABC India"},
  {  value: "Abhinav Capital",  label: "Abhinav Capital"},
  {  value: "Abhinav Leasing",  label: "Abhinav Leasing"},
  {  value: "Abhishek Finle.",  label: "Abhishek Finle."},
  {  value: "Abhishek Infra.",  label: "Abhishek Infra."},
  {  value: "Abhishek Integr.",  label: "Abhishek Integr."},
  {  value: "Abirami Fin.",  label: "Abirami Fin."},
  {  value: "ABM Knowledge",  label: "ABM Knowledge"},
  {  value: "ACC",  label: "ACC"},
  {  value: "Accel",  label: "Accel"},
  {  value: "Accelya Solution",  label: "Accelya Solution"},
  {  value: "Accord Synergy",  label: "Accord Synergy"},
  {  value: "Accuracy Shippi.",  label: "Accuracy Shippi."},
  {  value: "ACE EduTremd Ltd",  label: "ACE EduTremd Ltd"},
  {  value: "Ace Integrated",  label: "Ace Integrated"},
  {  value: "Ace Men",  label: "Ace Men"},
  {  value: "Ace Soft. Exp.",  label: "Ace Soft. Exp."},
  {  value: "Acewin Agriteck",  label: "Acewin Agriteck"},
  {  value: "ACI Infocom",  label: "ACI Infocom"},
  {  value: "Acknit Indus.",  label: "Acknit Indus."},
  {  value: "Acme Resources",  label: "Acme Resources"},
  {  value: "Acrow India",  label: "Acrow India"},
  {  value: "Acrysil",  label: "Acrysil"},
  {  value: "Action Const.Eq.",  label: "Action Const.Eq."},
  {  value: "Action Fin.Serv",  label: "Action Fin.Serv"},
  {  value: "Active Clothing",  label: "Active Clothing"},
  {  value: "AD Manum Finance",  label: "AD Manum Finance"},
  {  value: "Adani Enterp.",  label: "Adani Enterp."},
  {  value: "Adani Green",  label: "Adani Green"},
  {  value: "Adani Ports",  label: "Adani Ports"},
  {  value: "Adani Power",  label: "Adani Power"},
  {  value: "Adani Total Gas",  label: "Adani Total Gas"},
  {  value: "Adani Transmissi",  label: "Adani Transmissi"},
  {  value: "Adarsh Plant",  label: "Adarsh Plant"},
  {  value: "ADC India",  label: "ADC India"},
  {  value: "Adcon Capital",  label: "Adcon Capital"},
  {  value: "Addi Industries",  label: "Addi Industries"},
  {  value: "Add-Shop E-Reta.",  label: "Add-Shop E-Reta."},
  {  value: "Adeshwar Meditex",  label: "Adeshwar Meditex"},
  {  value: "ADF Foods",  label: "ADF Foods"},
  {  value: "Adinath Exim Res",  label: "Adinath Exim Res"},
  {  value: "Adinath Textiles",  label: "Adinath Textiles"},
  {  value: "Adishakti Loha",  label: "Adishakti Loha"},
  {  value: "Adit.Birla Money",  label: "Adit.Birla Money"},
  {  value: "Aditri Industrie",  label: "Aditri Industrie"},
  {  value: "Aditya AMC",  label: "Aditya AMC"},
  {  value: "Aditya Bir. Fas.",  label: "Aditya Bir. Fas."},
  {  value: "Aditya Birla Cap",  label: "Aditya Birla Cap"},
  {  value: "Aditya Consumer",  label: "Aditya Consumer"},
  {  value: "Aditya Ispat",  label: "Aditya Ispat"},
  {  value: "Aditya Spinners",  label: "Aditya Spinners"},
  {  value: "Aditya Vision",  label: "Aditya Vision"},
  {  value: "Adjia Tech",  label: "Adjia Tech"},
  {  value: "Ador Fontech",  label: "Ador Fontech"},
  {  value: "Ador Multi Prod.",  label: "Ador Multi Prod."},
  {  value: "Ador Welding",  label: "Ador Welding"},
  {  value: "Adroit Info.",  label: "Adroit Info."},
  {  value: "Advait Infratech",  label: "Advait Infratech"},
  {  value: "Advance Lifes.",  label: "Advance Lifes."},
  {  value: "Advance Meter.",  label: "Advance Meter."},
  {  value: "Advance Petroch.",  label: "Advance Petroch."},
  {  value: "Advance Syntex",  label: "Advance Syntex"},
  {  value: "Advanced Enzyme",  label: "Advanced Enzyme"},
  {  value: "Advani Hotels.",  label: "Advani Hotels."},
  {  value: "Advent Computer",  label: "Advent Computer"}
  
]

export default arrNames;